"""Add shop backdating config

Revision ID: acc38e8c9926
Revises: a3b8c4d5e6f7
Create Date: 2026-06-29 11:52:22.392579
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'acc38e8c9926'
down_revision: Union[str, None] = 'a3b8c4d5e6f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_backdate_policy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('allow_shop_backdated_inventory', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('shop_backdate_window_days', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_backdate_policy'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory_backdate_policy')
    # ### end Alembic commands ###
