"""movement splits

Revision ID: de470739b85b
Revises: 0028_user_last_login
Create Date: 2026-06-22 14:47:11.054509
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'de470739b85b'
down_revision: Union[str, None] = '0028_user_last_login'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_movement_splits',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('movement_id', sa.Uuid(), nullable=False),
    sa.Column('category_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_inventory_movement_splits_ck_inventory_movement_splits_quantity_positive')),
    sa.ForeignKeyConstraint(['category_id'], ['inventory_categories.id'], name=op.f('fk_inventory_movement_splits_category_id_inventory_categories'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['movement_id'], ['inventory_movements.id'], name=op.f('fk_inventory_movement_splits_movement_id_inventory_movements'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_inventory_movement_splits'))
    )
    op.create_index(op.f('ix_inventory_movement_splits_category_id'), 'inventory_movement_splits', ['category_id'], unique=False)
    op.create_index(op.f('ix_inventory_movement_splits_created_at'), 'inventory_movement_splits', ['created_at'], unique=False)
    op.create_index(op.f('ix_inventory_movement_splits_id'), 'inventory_movement_splits', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_movement_splits_movement_id'), 'inventory_movement_splits', ['movement_id'], unique=False)
    op.create_index(op.f('ix_expense_entries_created_at'), 'expense_entries', ['created_at'], unique=False)
    op.create_index(op.f('ix_expense_entries_expense_item_id'), 'expense_entries', ['expense_item_id'], unique=False)
    op.create_index(op.f('ix_expense_entries_id'), 'expense_entries', ['id'], unique=False)
    op.create_index(op.f('ix_expense_entries_shop_id'), 'expense_entries', ['shop_id'], unique=False)
    op.drop_column('expense_entries', 'updated_at')
    op.create_index(op.f('ix_expense_items_created_at'), 'expense_items', ['created_at'], unique=False)
    op.create_index(op.f('ix_expense_items_id'), 'expense_items', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_categories_created_at'), 'inventory_categories', ['created_at'], unique=False)
    op.create_index(op.f('ix_inventory_categories_id'), 'inventory_categories', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_item_billing_mappings_created_at'), 'inventory_item_billing_mappings', ['created_at'], unique=False)
    op.create_index(op.f('ix_inventory_item_billing_mappings_id'), 'inventory_item_billing_mappings', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_item_categories_category_id'), 'inventory_item_categories', ['category_id'], unique=False)
    op.create_index(op.f('ix_inventory_item_categories_created_at'), 'inventory_item_categories', ['created_at'], unique=False)
    op.create_index(op.f('ix_inventory_item_categories_id'), 'inventory_item_categories', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_item_categories_inventory_item_id'), 'inventory_item_categories', ['inventory_item_id'], unique=False)
    op.drop_index(op.f('ix_inventory_items_lower_name_trgm'), table_name='inventory_items', postgresql_ops={'lower(name::text)': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('ix_inventory_items_lower_tamil_name_trgm'), table_name='inventory_items', postgresql_ops={'lower(tamil_name::text)': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('ix_inventory_items_created_at'), 'inventory_items', ['created_at'], unique=False)
    op.create_index(op.f('ix_inventory_items_id'), 'inventory_items', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_category_id'), 'inventory_movements', ['category_id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_created_at'), 'inventory_movements', ['created_at'], unique=False)
    op.create_index(op.f('ix_inventory_movements_id'), 'inventory_movements', ['id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_inventory_item_id'), 'inventory_movements', ['inventory_item_id'], unique=False)
    op.create_index(op.f('ix_inventory_movements_shop_id'), 'inventory_movements', ['shop_id'], unique=False)
    op.drop_index(op.f('ix_items_catalogue_active_sort_lower_name'), table_name='items', postgresql_where='((shop_id IS NULL) AND (is_active IS TRUE))')
    op.drop_index(op.f('ix_items_catalogue_sort_lower_name'), table_name='items', postgresql_where='(shop_id IS NULL)')
    op.drop_index(op.f('ix_items_lower_name_trgm'), table_name='items', postgresql_ops={'lower(name::text)': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('ix_items_lower_tamil_name_trgm'), table_name='items', postgresql_ops={"lower(COALESCE(tamil_name, ''::character varying)::text)": 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('ix_items_name_trgm'), table_name='items', postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('ix_items_shop_sort_lower_name'), table_name='items', postgresql_where='(shop_id IS NOT NULL)')
    op.drop_index(op.f('ix_items_tamil_name_trgm'), table_name='items', postgresql_ops={'tamil_name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('ux_items_global_name_lower'), table_name='items', postgresql_where='(shop_id IS NULL)')
    op.drop_index(op.f('ux_items_shop_name_lower'), table_name='items', postgresql_where='(shop_id IS NOT NULL)')
    op.create_index(op.f('ix_shop_expense_allocations_created_at'), 'shop_expense_allocations', ['created_at'], unique=False)
    op.create_index(op.f('ix_shop_expense_allocations_expense_item_id'), 'shop_expense_allocations', ['expense_item_id'], unique=False)
    op.create_index(op.f('ix_shop_expense_allocations_id'), 'shop_expense_allocations', ['id'], unique=False)
    op.create_index(op.f('ix_shop_expense_allocations_shop_id'), 'shop_expense_allocations', ['shop_id'], unique=False)
    op.create_index(op.f('ix_shop_inventory_allocations_created_at'), 'shop_inventory_allocations', ['created_at'], unique=False)
    op.create_index(op.f('ix_shop_inventory_allocations_id'), 'shop_inventory_allocations', ['id'], unique=False)
    op.create_index(op.f('ix_shop_inventory_allocations_inventory_item_id'), 'shop_inventory_allocations', ['inventory_item_id'], unique=False)
    op.create_index(op.f('ix_shop_inventory_allocations_shop_id'), 'shop_inventory_allocations', ['shop_id'], unique=False)
    op.drop_index(op.f('ix_shop_item_allocations_lower_display_name_trgm'), table_name='shop_item_allocations', postgresql_ops={"lower(COALESCE(display_name, ''::character varying)::text)": 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('ix_shop_item_allocations_lower_tamil_name_trgm'), table_name='shop_item_allocations', postgresql_ops={"lower(COALESCE(tamil_name, ''::character varying)::text)": 'gin_trgm_ops'}, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_shop_item_allocations_lower_tamil_name_trgm'), 'shop_item_allocations', [sa.literal_column("lower(COALESCE(tamil_name, ''::character varying)::text)")], unique=False, postgresql_ops={"lower(COALESCE(tamil_name, ''::character varying)::text)": 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('ix_shop_item_allocations_lower_display_name_trgm'), 'shop_item_allocations', [sa.literal_column("lower(COALESCE(display_name, ''::character varying)::text)")], unique=False, postgresql_ops={"lower(COALESCE(display_name, ''::character varying)::text)": 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('ix_shop_inventory_allocations_shop_id'), table_name='shop_inventory_allocations')
    op.drop_index(op.f('ix_shop_inventory_allocations_inventory_item_id'), table_name='shop_inventory_allocations')
    op.drop_index(op.f('ix_shop_inventory_allocations_id'), table_name='shop_inventory_allocations')
    op.drop_index(op.f('ix_shop_inventory_allocations_created_at'), table_name='shop_inventory_allocations')
    op.drop_index(op.f('ix_shop_expense_allocations_shop_id'), table_name='shop_expense_allocations')
    op.drop_index(op.f('ix_shop_expense_allocations_id'), table_name='shop_expense_allocations')
    op.drop_index(op.f('ix_shop_expense_allocations_expense_item_id'), table_name='shop_expense_allocations')
    op.drop_index(op.f('ix_shop_expense_allocations_created_at'), table_name='shop_expense_allocations')
    op.create_index(op.f('ux_items_shop_name_lower'), 'items', ['shop_id', sa.literal_column('lower(name::text)')], unique=True, postgresql_where='(shop_id IS NOT NULL)')
    op.create_index(op.f('ux_items_global_name_lower'), 'items', [sa.literal_column('lower(name::text)')], unique=True, postgresql_where='(shop_id IS NULL)')
    op.create_index(op.f('ix_items_tamil_name_trgm'), 'items', ['tamil_name'], unique=False, postgresql_ops={'tamil_name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('ix_items_shop_sort_lower_name'), 'items', ['shop_id', 'sort_order', sa.literal_column('lower(name::text)'), 'id'], unique=False, postgresql_where='(shop_id IS NOT NULL)')
    op.create_index(op.f('ix_items_name_trgm'), 'items', ['name'], unique=False, postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('ix_items_lower_tamil_name_trgm'), 'items', [sa.literal_column("lower(COALESCE(tamil_name, ''::character varying)::text)")], unique=False, postgresql_ops={"lower(COALESCE(tamil_name, ''::character varying)::text)": 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('ix_items_lower_name_trgm'), 'items', [sa.literal_column('lower(name::text)')], unique=False, postgresql_ops={'lower(name::text)': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('ix_items_catalogue_sort_lower_name'), 'items', ['sort_order', sa.literal_column('lower(name::text)'), 'id'], unique=False, postgresql_where='(shop_id IS NULL)')
    op.create_index(op.f('ix_items_catalogue_active_sort_lower_name'), 'items', ['sort_order', sa.literal_column('lower(name::text)'), 'id'], unique=False, postgresql_where='((shop_id IS NULL) AND (is_active IS TRUE))')
    op.drop_index(op.f('ix_inventory_movements_shop_id'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_inventory_item_id'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_id'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_created_at'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_movements_category_id'), table_name='inventory_movements')
    op.drop_index(op.f('ix_inventory_items_id'), table_name='inventory_items')
    op.drop_index(op.f('ix_inventory_items_created_at'), table_name='inventory_items')
    op.create_index(op.f('ix_inventory_items_lower_tamil_name_trgm'), 'inventory_items', [sa.literal_column('lower(tamil_name::text)')], unique=False, postgresql_ops={'lower(tamil_name::text)': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('ix_inventory_items_lower_name_trgm'), 'inventory_items', [sa.literal_column('lower(name::text)')], unique=False, postgresql_ops={'lower(name::text)': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('ix_inventory_item_categories_inventory_item_id'), table_name='inventory_item_categories')
    op.drop_index(op.f('ix_inventory_item_categories_id'), table_name='inventory_item_categories')
    op.drop_index(op.f('ix_inventory_item_categories_created_at'), table_name='inventory_item_categories')
    op.drop_index(op.f('ix_inventory_item_categories_category_id'), table_name='inventory_item_categories')
    op.drop_index(op.f('ix_inventory_item_billing_mappings_id'), table_name='inventory_item_billing_mappings')
    op.drop_index(op.f('ix_inventory_item_billing_mappings_created_at'), table_name='inventory_item_billing_mappings')
    op.drop_index(op.f('ix_inventory_categories_id'), table_name='inventory_categories')
    op.drop_index(op.f('ix_inventory_categories_created_at'), table_name='inventory_categories')
    op.drop_index(op.f('ix_expense_items_id'), table_name='expense_items')
    op.drop_index(op.f('ix_expense_items_created_at'), table_name='expense_items')
    op.add_column('expense_entries', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_expense_entries_shop_id'), table_name='expense_entries')
    op.drop_index(op.f('ix_expense_entries_id'), table_name='expense_entries')
    op.drop_index(op.f('ix_expense_entries_expense_item_id'), table_name='expense_entries')
    op.drop_index(op.f('ix_expense_entries_created_at'), table_name='expense_entries')
    op.drop_index(op.f('ix_inventory_movement_splits_movement_id'), table_name='inventory_movement_splits')
    op.drop_index(op.f('ix_inventory_movement_splits_id'), table_name='inventory_movement_splits')
    op.drop_index(op.f('ix_inventory_movement_splits_created_at'), table_name='inventory_movement_splits')
    op.drop_index(op.f('ix_inventory_movement_splits_category_id'), table_name='inventory_movement_splits')
    op.drop_table('inventory_movement_splits')
    # ### end Alembic commands ###
