"""Add purchase_rate to InventoryItem

Revision ID: fb0d2b791bbc
Revises: 1fb8087fddba
Create Date: 2026-06-22 15:38:07.588869
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fb0d2b791bbc'
down_revision: Union[str, None] = '1fb8087fddba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inventory_items', sa.Column('purchase_rate', sa.Numeric(precision=12, scale=2), server_default=sa.text('0.00'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('inventory_items', 'purchase_rate')
    # ### end Alembic commands ###
